version: '4'
services:
    mongodb:
      image: mongo:7.0.5
      container_name: mongodb
      ports:
            - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root  # Admin username for MongoDB
        MONGO_INITDB_ROOT_PASSWORD: password  # Admin password for MongoDB
        MONGO_INITDB_ROOT_DATABASE: product-service  # MongoDB service name
      volumes:
        - /home/khimani/Downloads/product-service/data:/data/db #ensures that data is stored persistently even if the container is removed or restarted.